Step2
zuniors/java-racingcar pull request #1
Opened 2020-05-12 01:17 UTC by gmlwjd9405

2020-05-12 04:34 UTC, nokchax requested changes
수고했어요ㅋㅋㅋㅋ 깔끔하게 잘 짰네요, 커밋도 잘 나눠뒀구요 😄
이후에 추가적인 연산자가 생겨도 큰 변경 없이도, 잘 돌아가도록 짰고,
전체적으로 잘하겠다는 의지가 뿜뿜거리는 코드였습니다 👍 ㅎㅎ
생각해 볼만한 코멘트 하나 남겨뒀습니다.

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/calculator/Calculator.java
> +    }
생성자를 하나도 생성하지 않으면 컴파일러가 기본 생성자를 클래스와 같은 public으로 생성하죠,
외부에서 기본 생성자 접근을 막기위해 기본생성자를 아래처럼 명시해주면 더 좋을거 같아요 :)
```
    private Calculator() {}
```

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/exception/ErrorMessage.java
> +}
깔끔하니 좋네요 👍 
여기도 기본 생성자를 private으로 명시해 두는게 좋을거 같아요

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/calculator/Calculator.java
> +        }
validate(input) 이라는 함수로 따로 빼는건 어떨까요?
추후에 인풋값이 추가되거나 검증할 것이 늘어나면 해당 코드가 늘어나겠죠?
검증이라는 하나의 작업 단위로 메소드 분리를 하면 더 깔끔해 질 것 같습니다.

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/calculator/Calculator.java
> +        }
try catch는 별도의 함수로 분리하는게 가독성 면에서 더 좋아요,
아래는 clean code 가이드에 있는 문굽니다.
``try/catch 블록은 원래 추하다. 코드 구조에 혼란을 일으키며, 정상적인 동작과 오류 처리 동작을 뒤섞는다. try/catch 블록을 별도 함수로 뽑아내는 편이 낫다.``

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/calculator/Calculator.java
> +        int operandA = StringUtil.toInt(values[0]);
operandA,B 보다는 operandX,Y 처럼 좀 더 수학에서 사용하는 변수명 같이 하면 어떨까요?

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/operation/OperationStrategy.java
> +}
비슷한 작업을 해주는 Function, BiFunction 인터페이스가 있어요
그래도 FunctionalInterface까지 만드시다니 👍

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperationStrategy.java
> +    }
현재는 OperationStrategy를 구현하기 때문에 각 enum이 해당 인터페이스를 구현해야 하는 구조인데,
구현하지 않고 필드로 가지고 있으면 다음과 같이 구현이 가능해요, 
```
public enum ArithmeticOperationStrategy {
    PLUS("+", (x, y) -> x + y),
    MINUS("-", (x, y) -> x - y),
    TIMES("*", (x, y) -> x * y),
    DIVIDE("/", (x, y) -> x / y);

    private final String expression;
    private final OperationStrategy operation;

    ArithmeticOperationStrategy(final String expression, final OperationStrategy operation) {
        this.expression = expression;
        this.operation = operation;
    }
}

```

여기서 조금만 더 욕심을 내보자면, BiFunction을 이용해서 다음처럼 구현할 수 있어요
```
public enum ArithmeticOperation {
    PLUS("+", Math::addExact),
    MINUS("-", Math::subtractExact),
    TIMES("*", Math::multiplyExact),
    DIVIDE("/", Math::floorDiv);

    private final String expression;
    private final BiFunction<Integer, Integer, Integer> function;

    ArithmeticOperation(final String expression, final BiFunction<Integer, Integer, Integer> function) {
        this.expression = expression;
        this.function = function;
    }
    
    public int calculate(int x, int y) {
        return function.apply(x, y);
    }
}
```

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperationStrategy.java
> +    private String expression;
`Enum` 내의 필드는 불변이기 때문에 `final`을 붙여주는게 좋을거 같아요

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperationStrategy.java
> +    }
코멘트는 많이 했지만, if/else 없이 enum 추가만으로도 새로운 연산자를 추가할 수 있는 확장성 있는 구조로 잘 만드셨습니다 😄

2020-05-12 04:34 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperationStrategy.java
> +    }
of함수를 이용하면 매번 stream으로 연산자 문자에 해당하는 Enum을 찾겠죠?
for문이나 stream사용없이 한번에 문자에 대한 enum을 찾아서 반환할순 없을까요?

2020-05-12 04:34 UTC, nokchax commented on src/test/java/calculator/calculator/CalculatorTest.java
> +    private static Stream<Arguments> basicCase() {
이미 알고 계실수도 있겠지만
@MethodSource의 값으로 함수명을 기입하지 않고, 동일한 함수명을 사용할 수 있어요
```suggestion
    @ParameterizedTest
    @MethodSource
    void success(final String value, final int expected) {
        assertThat(calculator.run(value)).isEqualTo(expected);
    }

    private static Stream<Arguments> success() {
        ...
    }
```

2020-05-12 09:21 UTC, gmlwjd9405 commented on src/main/java/calculator/exception/ErrorMessage.java
> +}
해당 클래스에 대한 생성자를 사용할 일이 없을 거 같은데, 여기서도 private 기본 생성자를 명시할 필요가 있는 건가요? :question:

2020-05-12 09:26 UTC, gmlwjd9405 commented on src/main/java/calculator/operation/OperationStrategy.java
> +}
BiFunction 으로 리팩토링 하여 다시 pr 날릴 계획입니다! :smile:

2020-05-12 09:37 UTC, gmlwjd9405 commented on src/main/java/calculator/operation/ArithmeticOperationStrategy.java
> +    }
오 Math 에 저런 메서드들도 있었네요. 👍

2020-05-12 09:39 UTC, gmlwjd9405 commented on src/test/java/calculator/calculator/CalculatorTest.java
> +    private static Stream<Arguments> basicCase() {
넵!! 알고 있었지만 remind 감사합니다 ㅎㅎ

2020-05-12 10:01 UTC, nokchax commented on src/main/java/calculator/exception/ErrorMessage.java
> +}
이 클래스를 구현한 목적은 객체를 생성하고 활용하는 것이 아니기 때문에 기본 생성자를 명시적으로 막아두는게 좋다고 생각해요.

 기본 생성자가 생성가능해면, 단순히 객체가 생성가능한 것 뿐만아니라 해당 클래스에 대한 상속도 가능해져요.
 단순히 이런 간단한 프로젝트 내부에서만 사용하는 코드가 아니라, 널리 사용되는 라이브러리 혹은 프레임워크에서, 클래스의 개발자 의도와는 다르게 해당 클래스에 대해 상속이 가능해지죠. 물론 상속이나 객체 생성이 가능해진다고 크게 문제될 건 없지만, 이 클래스를 사용하는 사용자에게 명확한 의미 전달이 될거 같다고 생각하는데 어떻게 생각하세요?

 참고로 private 생성자에 대한 내용은 이팩티브 자바 2판 기준 규칙4 를 참고하시면 돼요 😃

2020-05-12 11:31 UTC, gmlwjd9405 commented on src/main/java/calculator/exception/ErrorMessage.java
> +}
이 클래스를 구현한 목적이 '객체를 생성하고 활용하는 것이 아니다'라는 것을 사용자에게 명확하게 전달한다는 의미가 있겠네요! ㅎㅎㅎ 
구체적인 설명과 참조 감사합니다! :smile:

2020-05-12 11:50 UTC, gmlwjd9405 commented on src/main/java/calculator/operation/ArithmeticOperationStrategy.java
> +    }
Hint: [https://sjh836.tistory.com/175](https://sjh836.tistory.com/175)

2020-05-12 14:35 UTC, nokchax approved these changes
고생했어요 ㅎㅎ.
전보다 간결하고 깔끔해졌네요 👏👏👏 
이대로 끝내도 되지만, 팁이랑 코멘트 조금 남겼어요.
우선 코드 승인은 해둘게요! 수정하시면 추가리뷰 없이 바로 머지하는걸로 하겠습니다.

2020-05-12 14:35 UTC, nokchax commented on src/main/java/calculator/calculator/StringCalculator.java
> +        this.validateInputValues(values);
`validateInputValues()`는 `caculate()` 첫줄에서 호출하는게, 관련있는 코드는 묶어주는 관점에서 더 좋을거 같아요

2020-05-12 14:35 UTC, nokchax commented on src/main/java/calculator/calculator/StringCalculator.java
> +            result = operator.operate(result, StringUtil.toInt(getToken(values, i, 1)));
0, 1 같은 매직넘버는 상수로 빼서 어떤의미인지 잘 나타낼수 있도록 해보죠

2020-05-12 14:35 UTC, nokchax commented on src/main/java/calculator/calculator/StringCalculator.java
> +    }
👍

2020-05-12 14:35 UTC, nokchax commented on src/main/java/calculator/exception/ErrorMessage.java
> +    private ErrorMessage() {}
👍

2020-05-12 14:35 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperation.java
> +    public static final Map<String, ArithmeticOperation> map = new HashMap<>();
map보다는 OPERATIONS 같은 의미있는 변수명을 쓰도록 해요,
그리고 static 이니까 대문자로!

2020-05-12 14:35 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperation.java
> +        throw new IllegalArgumentException(String.format(ErrorMessage.NOT_SUPPORTED_ARITHMETIC, expression));
```suggestion
        if (!map.containsKey(expression)) {
            throw new IllegalArgumentException(String.format(ErrorMessage.NOT_SUPPORTED_ARITHMETIC, expression));
        }
        return map.get(expression);
```
이런 방식이 더 보편적이지 않을까요?
지금이야 return만 하기때문에 if문 내부가 길지 않아서 보지 흉하지 않지만, 로직이 조금만 추가되면, if문 내부에서 예외를 던져주는게 훨씬 깔끔할거 같아요.

코드에 통일성을 주기 위해서 위처럼 처리하는걸 권장해주고 싶네요 ㅎㅎ

2020-05-12 14:35 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperation.java
> +    }
💯 
아주 약간만 더 손보자면 아래처럼 구현할 수 있어요
```suggestion
    public static final Map<String, ArithmeticOperation> OPERATIONS =
              Arrays.stream(ArithmeticOperation.values())
                         .collect(Collectors.toMap(ArithmeticOperation::getExpression, Function.identity()));
    
    private String getExpression() { return expression; }
```
잘 하셨어요😄

2020-05-12 14:50 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperation.java
> +    }
아차 그리고 외부에서는 사용할일이 없으니 `private` access modifier를 사용하는게 좋겠네요

2020-05-12 16:27 UTC, gmlwjd9405 commented on src/main/java/calculator/operation/ArithmeticOperation.java
> +    }
생성과 동시에 초기화 하는 방법이 좋을거 같네요! ㅎㅎ

```Collectors.toMap(ArithmeticOperation::getExpression, Function.identity())```
- 단지 람다식을 이용하기 위해 private getter method 를 추가할 필요가 있을까 하는 궁금증이 생기네요 ❓ 
- 람다식의 장점과 어떤 경우에는 stream 대신 단순 반복문을 사용하는 것이 효율적인지에 대해서도 알아봐야 할 거 같아요!

2020-05-12 16:28 UTC, gmlwjd9405 commented on src/main/java/calculator/operation/ArithmeticOperation.java
> +    public static final Map<String, ArithmeticOperation> map = new HashMap<>();
static 의 경우 대문자 변수명을 사용하는 습관을 들여야겠네요! 😄

2020-05-12 22:01 UTC, merged

2020-05-13 00:36 UTC, nokchax commented on src/main/java/calculator/operation/ArithmeticOperation.java
> +    }
음 `getter`라고 하더라도 `private`이기 때문에 큰 문제 없지 않을까요??