Step3 - 자동차 경주
zuniors/java-racingcar pull request #3
Opened 2020-05-13 12:50 UTC by gmlwjd9405

2020-05-13 16:45 UTC, nokchax requested changes
수고하셨습니다 :)

구조가 깔끔하네요, 인터페이스 활용도 잘 했고 테스트도 잘 짜셨고, 커밋 단위도 잘게 나누어서 잘 하셨습니다. 💯 

아쉬운점은 네이밍! 읽기 좋은 코드를 짜기 위해서 중요한 능력중 하나니까 앞으로 더 좋은 변수명, 메소드명 을 짓기 위해 고민해보도록 해요. 그리고 커밋할때 아직은 TDD를 적용하지 않으시는거 같아요 처음이라 힘드시겠지만 TDD적용해 보도록해요. 저도 아직까지 힘들어요ㅋㅋㅋ

그리고 고민을 많이 해봐야할 점. 비즈니스 로직과 UI를 분리해서 비즈니스 로직에 UI가 영향을 받지 않도록 하려면 어떻게 해야할지 고민해 보시길 바래요 :)

리뷰를 많이 남기긴 했는데 ㅎㅎ.. 제가 처음 짠 코드에 비하면 정말 잘 짜셨고 잘하고 계시니까 낙담하진 마시구, 끝까지 열심히 하세요 파이팅 😁

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/exception/ErrorMessage.java
> +    public static final String INVALID_PARAMETER = "유효하지 않은 입력값입니.";
오타 ㅎㅎ

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/moving/MovingStrategy.java
> +    boolean move();
boolean값을 리턴하는 함수 작명에 대한 [링크](https://soojin.ro/blog/naming-boolean-variables) 참고해보세요 :)
```java
boolean isEditable(); //편집할 수 있는가?
boolean isEditing(); //편집 중인가?
boolean canEdit(); //편집할 수 있는가? -> 다음 '조동사 용법' 섹션 참고
```

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/Car.java
> +    }
접근 제한자가 생략되어 있기도 하고 붙어있기도 하네요?
의도해서 생략하신건가요?

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/Racing.java
> +                .limit(numOfCar)
이런 방식은 처음봐요 잘 배우고 갑니다 👍

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/Racing.java
> +    }
이번 과제에서 제시하고 있는 클린코드 가이드 중 하나입니다.
```
명령과 조회를 분리하라.
- 함수는 무언가를 수행하거나 답하거나 둘 중 하나만 해야함.
- 개체 상태를 변경하거나, 개체 정보를 반환하거나.
```
이렇게 하나의 함수 내에서 두 가지를 동시에 하면 나중에 혼란을 야기할수 있어요.

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/exception/ErrorMessage.java
> +    private ErrorMessage() {}
👏👏👏

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
```suggestion
        return new Random().nextInt(MAX_NUM) + MIN_NUM;
```
굳이 클래스까지 붙여준 이유가 있나요?

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
java api문서를 긁어왔슴다...
```
public int nextInt(int bound)
...
Parameters:
bound - the upper bound (exclusive). Must be positive.
```
MAX를 9로 설정해 두셨는데 `exclusive` 라서 0\~8까지의 값만 나오는걸 아시고 하신건가요?
요구사항에서는 0\~9까지였는데 혹시나 착각하신건지 아니면  exclusive를 모르고 계신건지 몰라서 남겨봤어요

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/Car.java
> +    static Car of() {
정적 팩토리 메소드를 사용하셨는데, 함수명이 어색하네요 `~의` 라는 의미라서 무항보다는 특정 파라미터가 있을때 어울릴거 같습니다. 무항일 경우에는 `Car.newInstance()` 혹은 그냥 `new Car()`를 사용하는게 좋아보여요

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/Car.java
> +    }
테스트 클래스에서 접근하려고 기본 생성자를 붙인거 같기도하고 🤔🤔🤔

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +    private static final String LOOP_COUNT = "시도할 횟수는 몇 회 인가요?";
요 변수들은 `InputView`쪽에 모으는게 나아보이는데 어떻게 생각하세요?
함수의 재사용을 위해서 이렇게 빠지게 된거 같은데,
```
InputView.inputNumOfCar();
InputView.inputLoopCount();
```
함수를 만들고 내부에서 input() 함수를 재사용하는건 어떨까요?

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/view/InputView.java
> +    }
```suggestion
    private static int validatedInt() {
        int input = SCANNER.nextInt();
        if (input < 0) {
            throw new IllegalArgumentException(ErrorMessage.MORE_THAN_ZERO);
        }
        return input;
    }
```
이런 방식은 어때요?

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/Racing.java
> +    private void validateInput(final int input, final MovingStrategy movingStrategy) {
`input`이라는 변수명 보다는 더 자세한 변수명을 씁시다

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/Racing.java
> +        if (input < 0 || movingStrategy == null) {
`input`이 `0`이어도 레이싱이 성립 안하지 않을까요?

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/moving/MovingStrategy.java
> +public interface MovingStrategy {
interface 활용해서 변화에 잘 대응할 수 있는 코드로 만드셨고,
인터페이스를 활용해서 테스트도 잘 하셨어요 💯

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
매번 새로운 Random 객체를 생성할 필요가 있을까요?

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
이거는 적용하시지는 말고 한번 고민해보라는 뜻에서 남겨볼게요.

지금 보면 `RandomMovingStrategy`의 `move()` 에 대한 테스트는 없잖아요?
`random()`을 호출했을때 `4이상이면 true를 리턴하고, 미만이면 false를 리턴`하는데,
정말로 그렇게 동작하는지 테스트하고 싶으면 어떻게 해야할까요???

2020-05-13 16:45 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +        }
비지니스 로직과 UI에 관해서 생각해보셨으면 해서 남겨봐요.

추후에 자동차 경주를 콘솔이 아닌 웹을 통해서 보여주도록 바꿔야 하면 어떤 것들이 변하게 될까요?
로직이 변경됨에 따라 혹은 자동차 객체가 변화함에 따라 결과를 보여주는 것에도 영향이 가지 않게 하려면 혹은 영향을 최소화 하려면 어떻게 해야할까요?

UI를 그리는데 필요한 것들은 무엇인지, 이것을 어떻게 넘겨주고 보여줄 것인지 고민해보도록 해요 :)

2020-05-13 21:45 UTC, gmlwjd9405 commented on src/main/java/racingcar/exception/ErrorMessage.java
> +    public static final String INVALID_PARAMETER = "유효하지 않은 입력값입니.";
:sweat_smile:

2020-05-13 21:53 UTC, gmlwjd9405 commented on src/main/java/racingcar/Car.java
> +    }
맞습니다! 처음엔 private 이었다가 테스트 코드에서 사용할 때 접근이 안돼서 변경했습니다~
근데 테스트 코드를 위해 이렇게 접근자를 변경하는 것이 맞는지에 대해서는 조금 의문이 들긴 하네요.. :astonished:

2020-05-13 21:55 UTC, gmlwjd9405 commented on src/main/java/racingcar/Racing.java
> +                .limit(numOfCar)
참고: [https://www.geeksforgeeks.org/stream-generate-method-java/](https://www.geeksforgeeks.org/stream-generate-method-java/)

2020-05-13 22:03 UTC, gmlwjd9405 commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
그냥... 상수값에 대한 제 하나의 코딩 습관이라고 해야될까요....?ㅎㅎㅎ
동일한 클래스 내부에서 사용하는 거라면 간단하게 MAX_NUM 으로만 적어도 될 거 같아요!

2020-05-13 22:09 UTC, gmlwjd9405 commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
놀랍게도 둘 다 알고 있는 내용이었는데,
0~9 사이의 값이라고 해서 변수를 먼저 저렇게 적다보니까 구현할 때 실수가 나왔네요!ㅎㅎㅎ 수정하겠습니다. 👍

2020-05-13 22:26 UTC, gmlwjd9405 commented on src/main/java/racingcar/RacingGame.java
> +    private static final String LOOP_COUNT = "시도할 횟수는 몇 회 인가요?";
그렇네요, input 에 관련된 메시지니까 InputView 에 넣는 게 더 깔끔할 거 같아요!! 👍

2020-05-13 22:28 UTC, gmlwjd9405 commented on src/main/java/racingcar/view/InputView.java
> +    }
이 방식도 validate 와 return 을 한 메서드에서 처리하게 되는 거 같아 다른 메서드로 분리해서 변경하려고 합니다! 

```suggestion
    private static int input(String content) {
        System.out.println(content);
        int value = SCANNER.nextInt();
        validateInput(value);

        return value;
    }

    private static void validateInput(final int input) {
        if (input <= 0) {
            throw new IllegalArgumentException(ErrorMessage.MORE_THAN_ZERO);
        }
    }
```

2020-05-13 22:29 UTC, gmlwjd9405 commented on src/main/java/racingcar/Racing.java
> +    private void validateInput(final int input, final MovingStrategy movingStrategy) {
변수명은 늘 어렵네요.... 생각도 오래 해야돼서 좀만 대충 넘어가면 의미 파악이 어려운 메서드명이 되는 거 같아요.. :(

2020-05-13 22:30 UTC, gmlwjd9405 commented on src/main/java/racingcar/Racing.java
> +        if (input < 0 || movingStrategy == null) {
처음엔 차가 0대여도 뭐... 레이싱은 열릴 수도 있겠지 생각했는데...ㅋㅋㅋㅋㅋ
다시 생각해보니까 차가 없으면 성립이 안되는 게 맞네요ㅋㅋㅋㅋ :grin::grin::grin::grin:

2020-05-13 22:37 UTC, gmlwjd9405 commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
변수로 관리하도록 수정하겠습니다 :) 👍

2020-05-13 22:40 UTC, gmlwjd9405 commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +        return new Random().nextInt(RandomMovingStrategy.MAX_NUM) + RandomMovingStrategy.MIN_NUM;
(고민중)

2020-05-13 22:48 UTC, gmlwjd9405 commented on src/main/java/racingcar/RacingGame.java
> +        }
(생각중)

2020-05-14 04:14 UTC, nokchax commented on src/main/java/racingcar/Car.java
> +    }
음 저도 명확한 답을 할수 없어서 찾아봤는데요,
> 코드를 테스트 하려는 목적으로 클래스, 인터페이스를 접근 범위를 넓히는 것을 주의하라
`public 클래스의 private -> package-private으로 바꾸는거는 괜찮다. 하지만 그이상의 경우 공개 API에 문제가 될 수 있다.`

라고 하네요 ㅋㅋㅋ default(package-private) 접근제한자로 두는게 좋은 방법인거 같습니다.
이펙티브자바 3판기준 item15를 참고해보면 될거 같아요

2020-05-14 04:26 UTC, nokchax approved these changes
잘 반영했어요 ㅎㅎ
네이밍은 중요하니까 앞으로도 계속 신경써서 하도록 해보세요!
생각해 볼만한게 있어서 코멘트를 달았지만, 머지는 해두겠슴돠

2020-05-14 04:26 UTC, nokchax commented on src/main/java/racingcar/Car.java
> +    static Car newInstance() {
음 `DEFAULT_DISTANCE` 변수야 테스트 클래스에서 사용하니까 디폴트 접근제한자로 둔다고 쳐도.
나머지는 일반 코드에서도 사용하는 함수들인데 디폴트로 둘 이유가 있을까요?

2020-05-14 04:26 UTC, nokchax commented on src/main/java/racingcar/Racing.java
> +        cars = Stream.generate(Car::newInstance)
of보다 훨씬 읽기 좋네요 :) 👍

2020-05-14 04:26 UTC, nokchax commented on src/main/java/racingcar/Racing.java
> +    }
잘 나누셨습니다ㅎㅎ

2020-05-14 04:26 UTC, nokchax commented on src/main/java/racingcar/moving/MovingStrategy.java
> +    boolean isMovable();
좋은 네이밍입니다 :)

2020-05-14 04:26 UTC, merged

2020-05-14 06:19 UTC, gmlwjd9405 commented on src/main/java/racingcar/Car.java
> +    static Car newInstance() {
생성자와 move메서드를 디폴트 접근 제한자로 설정한 이유도 CarTest 에서 사용하기 때문인데, 제가 이해한게 맞나요? ❓

2020-05-14 06:54 UTC, nokchax commented on src/main/java/racingcar/Car.java
> +    static Car newInstance() {
음 지금 패키지 구조가
```
- racingcar
  - Car.java
  - Racing.java
  - RacingGame.java
  - exception
    - ErrorMessage.java
  - moving
    - MovingStrategy.java
    - RandomMovingStrategy.java
  - view
    - InputView.java
    - ResultView.java
```

이런식으로 되어있잖아요? Car라는 객체가 최상위 패키지에 있는데, 여기서 default 접근 제한자로 선언된 변수나 함수는 `Racing.java`, `RacingGame.java` 에서 밖에 참조를 못해요.

그런데 리팩토링중에 다음과 같이 패키지를 수정했다고 해볼게요
```
- racingcar
  - Racing.java
  - RacingGame.java
  - car
    - Car.java
  - exception
    - ErrorMessage.java
  - moving
    - MovingStrategy.java
    - RandomMovingStrategy.java
  - view
    - InputView.java
    - ResultView.java
```
이런 상태에서 Car의 내부의 함수, 변수에 default 접근제한자로 만들면 car 패키지 외부의 패키지에서는 Car의 default 접근제한자로 선언된 함수나 변수에 접근할 수 없죠.

그래서 `테스트에서 사용하기 위해서 default 접근제한자로 선언하면 안된다`고 생각해요. 정확히는 `클래스 내부, 그리고 테스트 클래스에서만 사용할때 default 접근 제한자로 선언` 해야한다고 생각합니다. 일반 코드에서 사용하는 필드, 코드는 public으로 선언하는게 좋지 않을까요?

이걸 알고 기본 생성자로 하셨다면 크게 상관없을거 같습니다. 다만 리팩토링을 하면서 패키지를 재조정하는 과정에서 혼란을 야기할수 있을거 같긴하네요 🤔

2020-05-15 11:56 UTC, gmlwjd9405 commented on src/main/java/racingcar/Car.java
> +    static Car newInstance() {
구체적인 설명 감사합니다!
패키지 구조를 변경해보면서 한 번 수정해보겠습니다. ㅎㅎ 👍