Step4 - 자동차 경주(우승자)
zuniors/java-racingcar pull request #5
Opened 2020-05-15 12:39 UTC by gmlwjd9405

2020-05-15 12:53 UTC, gmlwjd9405 commented
RandomMovingStrategy에 대한 테스트 코드를 작성하려고 하는데,
Random 이라는 통제할 수 없는 부분 때문에 좋은 방법이 떠오르지가 않네요... 😢 
좋은 방법이 없을까요? ❓

2020-05-15 14:48 UTC, nokchax requested changes
`1급 컬렉션` 잘 적용하셨어요! 이번 과제에 목표하지 않은 규칙인데, 적용한 덕분에 코드가 깔끔하네요. 
`1급 컬렉션`에 대해서도 생각해보시구, `인풋값 검증 로직`, `변수` 등이 어느 클래스에 있는게 좋을지 조금더 깊이 생각해보도록 해요!

고생하셨습니다. 😄😄

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Car.java
> +    private static void validateName(String name) {
final을 깜빡하셨군요

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +        List<Car> cars = Arrays.stream(carNames)
`carNames`가 null인 경우에는 `npe`가 발생하겠네요

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +                ).orElseGet(ArrayList::new);
승자가 없는 경우는 예외 상황이라고 봐야하지 않을까요?
`orElseThrow`가 나아보이는데 어떻게 생각하세요?

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +        MovingStrategy movingStrategy = new RandomMovingStrategy();
움직임 전략도 경주와 관련있는 객체 아닐까요?
기존에 Racing에 있던 `MovingStrategy`를 따로 빼신 이유가 있을까요?
단순히 도중에 변경가능하게 만들기 위해서라면, `Racing` 객체 생성시에 우선 한번 `MovingStrategy`를 넣어주고,
`void updateMovingStrategy(final MovingStrategy newMovingStrategy);` 같은 함수를 추가해서 변경해주는게 좋을거 같아요.

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Car.java
> +        validateName(name);
validate의 위치에 대해서 생각해보세요, 
어디에 검증 코드가 있는게 좋을지 고민해보셨으면 해요.
`private Car(final String name) {}` 를
`private static Car of(final String name) {}` 에서 뿐만아니라
다른 곳에서 호출하게 변경된다면, validateName 코드를 한번 더 써줘야겠죠?

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +                ).orElseGet(ArrayList::new);
지금 `getWinnerCars()`내부에서는 두가지 일을 하고 있죠,
```
1. 1등의 포지션 구하기
2. 1에서 구한 포지션과 동일한 포지션을 가진 car를 추려서 리턴하기
```
두가지 일을 한 호흡에 하려보니까 스트림 코드가 조금 길고, 뎊스도 깊어졌네요.
`getWinnerCars()` 내부에서 `int winnerPosition = getWinnerPosition();` 
같은 함수를 만들어 사용하면 더 간결해질거 같아요.
읽기 쉽고, 이해하기 쉬운 코드를 짜는게 우선입니다.

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +    private List<Car> cars;
1급 컬랙션을 벌써 적용하다닛 😮 👍 👍 👍

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +    private List<Car> cars;
1급 컬랙션을 적용했을때와 적용하지 않았을때, 
어떤 차이점이 있는지도 한번 짚어보고 넘어가셨으면 해요!
적용했을 때 어떤점이 좋은지!

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Racing.java
> +        this.cars = cars;
cars에 대한 검증이 필요할거 같아요

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/view/InputView.java
>      }
사용하지 않는다면 삭제하도록 합시다

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/view/InputView.java
>      private static final String NUM_OF_CAR_MESSAGE = "자동차 대수는 몇 대 인가요?";
이것도 사용하지 않으니 삭제하도록 합시다

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/view/InputView.java
> +            throw new IllegalArgumentException("aa");
예외 메세지! 깜빡하셨군요

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/util/StringUtil.java
> +
utils 클래스도 private 기본 생성자를 넣어주도록 해요

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/view/InputView.java
> +    private static final int MIN_NUM_OF_CARS = 0;
이것도 사용하지 않는 값이라 삭제가 필요한데, 그냥 코멘트 달아볼게요

InputView클래스의 역할은 뭘까요?
자동차의 최소값을 검증하는건 어디있는게 좋을까요?

위에도 달아뒀지만 검증코드의 위치에 대해서 한번 생각해보셨으면 해요.
구체적으로 설명달려다가 그냥 생각해보시라고 던집니다 😝

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/view/InputView.java
> +    private static String[] inputArray(final String message) {
배열 보다는 List사용이 낫지 않을까요?
배열을 사용하신 이유가 있나요?

2020-05-15 14:48 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +    );
이런 방식은 좋지 않은거 같아요 😦

2020-05-15 14:48 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +        assertThatCode(() -> Cars.of(carNames.get(3)))
get(number)이 무얼 의미하는지 왔다갔다 확인해야 하는데, 차라리 각가의 배열을 별개의 이름으로 따로 만들어 두는게 어떨까요?

2020-05-15 14:48 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
일부는 매번 움직이고, 일부는 매번 움직이지 않아서, 매번 움직인 차들만 리턴하는지 확인하고 싶으면 어떻게 테스트해야할까요?

2020-05-15 14:48 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
👍

2020-05-15 14:48 UTC, nokchax commented on src/test/java/racingcar/domain/CarTest.java
> +        Car car = Car.of("name");
동일한 이름으로 생성을 자주하는데 CarTest의 필드로 선언하고 `@BeforeEach` 로 초기화 시켜주는게 어떨까요?

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/view/ResultView.java
> +    }
지금이야 문제가 없는데, 이런방식의 코드는 동시성 문제로 예상치 못한 문제가 발생할수 있어서 각 메소드 내부에서 매번 StringBuilder를 새로 생성하는게 맞는거 같습니다. 🙅

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +        Racing racing = Racing.of(Cars.of(carNames));
레이싱 게임과 관련된 loopCount 값이 main에 있는게 맞을까요? 
main함수는 loopCount를 조작해서는 안될거 같은데 어떻게 생각하시나요? 🤔🤔🤔🤔

2020-05-15 14:48 UTC, nokchax commented on src/main/java/racingcar/domain/Racing.java
> +    private Cars cars;
지금은 필드에 `Cars`만 선언하고 사용하다보니까 `Racing 클래스`의 의미가 퇴색되는거 같아요
아래에서 볼수 있듯, `main`함수에서 `Cars`만 가지고도 동일한 일을 할 수 있죠?
```java
public static void main(String[] args) {
        String[] carNames = InputView.inputNameOfCars();
        int loopCount = InputView.inputLoopCount();

        Cars cars = Cars.of(carNames);
        MovingStrategy movingStrategy = new RandomMovingStrategy();

        ResultView.printResultMessage();
        for (int i = 0; i < loopCount; i++) {
            cars.moveCars(movingStrategy);
            ResultView.printResult(cars.getCars());
        }
        ResultView.printWinner(cars.getWinnerCars());
    }
```
어떤가요? 이정도면 `Racing 클래스`를 없애고,  `Cars클래스` 이름을 Racing으로 바꿔도 될거 같지않나요?

racing 객체가 좀 더 많은 일을 할수 있게 만들어봐요. 힌트를 조금 드리자면
loopCount 이상으로 run()명령이 들어왔을때 예외를 던지고 싶다면?
loopCount 만큼  run()하지 않았는데 winner를 호출하는 것을 막고 싶다면?
어떤식으로 객체를 구성하는게 좋을까요? 🤔🤔🤔🤔

2020-05-15 15:10 UTC, nokchax commented
> RandomMovingStrategy에 대한 테스트 코드를 작성하려고 하는데,
> Random 이라는 통제할 수 없는 부분 때문에 좋은 방법이 떠오르지가 않네요... 😢
> 좋은 방법이 없을까요? ❓

코드로 설명해드릴게요
```
public class RandomMoveStrategy implements MoveStrategy {
    private static final int MAXIMUM_NUM = 10;
    private static final int MOVE_STANDARD = 4;

    private final Random random;

    public RandomMoveStrategy() {
        this(new Random());
    }

    public RandomMoveStrategy(Random random) {
        this.random = random;
    }

    @Override
    public boolean isMovable() {
        return random.nextInt(MAXIMUM_NUM) >= MOVE_STANDARD;
    }
}
```
이런식으로  `RandomMoveStrategy객체`를 생성할때 `Random객체`를 받아오는 구조로 만들고 아래처럼 클래스를 만들어 넘기면 돼요

```
class TestRandom extends Random {
        private final int fixedValue;

        private TestRandom(final int fixedValue) {
            this.fixedValue = fixedValue;
        }

        private static TestRandom of(final int fixedValue) {
            return new TestRandom(fixedValue);
        }

        @Override
        public int nextInt(int bound) {
            return fixedValue;
        }
    }
```
그리고 아래처럼 넘겨주면 됩니다 :)
```
new RandomMoveStrategy(new TestRandom(5));
```
이러면러면 `isMovable()` 함수를 몇번이고 호출해도 true를 반환하겠죠?
이런식으로 테스트 하시면 돼요 헤헤..😃😃😃

2020-05-15 15:20 UTC, gmlwjd9405 commented on src/main/java/racingcar/RacingGame.java
> +        MovingStrategy movingStrategy = new RandomMovingStrategy();
**'Car가 이 MovingStrategy를 가지는게 저는 조금 더 자연스러운 구조인 것 같아요'**
라는 피드백을 받아서 수정했는데, 

1) Car 마다 경주 전략이 달라질 수 있다는 점에서 Racing 생성과 동시에 전략을 정하는 것이 맞지 않아서
2) 말씀하신 것처럼 도중에 전략을 쉽게 변경하기 위해서 
라는 판단에서 Racing에서 MovingStrategy 를 제거 했습니다. 2)번은 말씀하신 것처럼 해결이 될 거 같은데, 원래의 스트래티지 패턴에 따르면 Racing 에 전략을 두는 것이 맞는지도 좀 혼란스럽네요.. 😕 

조금 더 생각해 본 후에 다시 코멘트 남기도록 하겠습니다!

2020-05-15 15:27 UTC, gmlwjd9405 commented on src/main/java/racingcar/domain/Cars.java
> +    private List<Car> cars;
일급 컬렉션의 장점 
1. 비지니스에 종속적인 자료구조
2. Collection의 불변성을 보장
3. 상태와 행위를 한 곳에서 관리
4. 이름이 있는 컬렉션

참고: [https://jojoldu.tistory.com/412](https://jojoldu.tistory.com/412)

2020-05-15 15:37 UTC, gmlwjd9405 commented on src/main/java/racingcar/RacingGame.java
> +        Racing racing = Racing.of(Cars.of(carNames));
아래의 내용과 연결지어서 리팩토링 해보도록 하겠습니다! 👍

2020-05-15 16:00 UTC, gmlwjd9405 commented on src/main/java/racingcar/domain/Cars.java
> +                ).orElseGet(ArrayList::new);
그렇네요, 짤 때는 몰랐는데 이렇게 해야 메서드 당 하나의 일을 하게 되는 거 같아요 😄

2020-05-15 16:34 UTC, gmlwjd9405 commented on src/main/java/racingcar/view/InputView.java
> +    private static String[] inputArray(final String message) {
InputView 에서 String[] 을 List<String> 으로 변경하는 로직이 들어가는 것이 맞는지 잘 모르겠습니다.

단순히 입력받는 역할을 하는 클래스로 생각하자면, 
String[] -> List<String> 으로 변환하는 메서드를 모두 다른 영역으로 빼야할 것 같네요! :)

2020-05-15 16:35 UTC, gmlwjd9405 commented on src/main/java/racingcar/view/InputView.java
> +    private static final int MIN_NUM_OF_CARS = 0;
아래와 연결지어 같이 리팩토링 해보겠습니다. 👍

2020-05-15 17:06 UTC, gmlwjd9405 commented on src/main/java/racingcar/view/ResultView.java
> +    }
StringBuilder 를 기능이 분리된 메서드에서 사용하기 위해 그럼 인자로 계속해서 연쇄적으로 넘겨주는 것이 나을까요? 
지금이야 문제가 없더라도 수정을 하고는 싶은데 방법이 조금 고민 되네요...ㅎ 🤔 

조금 더 생각해 본 후에 다시 코멘트 남기도록 하겠습니다!

2020-05-16 01:03 UTC, gmlwjd9405 commented on src/test/java/racingcar/domain/CarsTest.java
> +    );
테스트할 대상 객체를 하나로 관리할 수 있는 방법을 조금 생각해봐야될 거 같아요. 😭

2020-05-16 01:15 UTC, gmlwjd9405 commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
짝수 번호에 대해서만 매번 움직이는 방법으로 수정해서 풀리퀘 날렸습니다. 👍 
확인해주시고 다시 코멘트 남겨주세요~ㅎㅎ

2020-05-16 01:35 UTC, gmlwjd9405 commented on src/main/java/racingcar/view/ResultView.java
> +    }
print 하는 역할과 print 하기 위한 String 값을 반환하는 메서드로 구분하니, 연쇄적으로 인자를 넘겨줄 필요가 없었네요 :) 
수정했습니다~ 👍

2020-05-16 04:04 UTC, nokchax approved these changes
원시값 래핑도 하시구.. 대단한걸요.... 😮😮 
몇가지 자잘한 코멘트랑, 의논해 보고 싶은점에 대해서 코멘트 남겼습니다.
크게 수정할건 없어서 승인해둘게요! 나머지 코멘트 답 남겨주시면 머지하겠습니다 ㅎㅎㅎ

고생했어요 👏👏👏👏

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +        while (!racing.isGameOver()) {
👍

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +    private int getWinnerPosition() {
👍

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +    }
훨씬 읽기 편해졌네요 😄

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +    public static final int BASE_LINE_NUM = 4;
이 클래스 내부랑 테스트를 위해서 사용하는 거라면 default가 낫지않을까요?

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +    private final Random random;
👍

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/util/StringUtil.java
> +    public static String[] splitValues(final String values, final String delimiter) {
👍

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/view/ResultView.java
> +            stringBuilder.append(getCarFinalPosition(car));
좋습니다 혹은 아래와 같은 방식도 괜찮아요
```java
private static void getCarNameWithSuffix(final Car car, final StringBuilder stringBuilder) {
    ....
}
```

2020-05-16 04:04 UTC, nokchax commented on src/test/java/racingcar/domain/CarTest.java
> +    }
👍

2020-05-16 04:04 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
조금 과한 감은 없지않아 있지만, 훨씬 좋네요 💯

2020-05-16 04:04 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +        private int value;
호옹 💯 👏👏👏

2020-05-16 04:04 UTC, nokchax commented on src/test/java/racingcar/moving/RandomMovingStrategyTest.java
> +public class RandomMovingStrategyTest {
👍

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/domain/Cars.java
> +    private static List<Car> toList(final String[] carNames) {
네이밍이 약간 아쉽네요 음... 뭔가 의미있는게 없을까요?
initCars 라던지..?

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/domain/Round.java
> +public class Round {
조금 과한 감도 있지만 잘 적용하셨어요!
`규칙 3: 모든 원시값과 문자열을 포장한다.`

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +        Racing racing = Racing.of(Cars.of(carNames), Round.of(round));
이건 그냥 의논해보고 싶어서 ㅎ..
이런 방식은 어떤거 같아요?
```
Racing racing = Racing.of(carNames, round);
```

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/domain/Car.java
> +    private static void validateName(final String name) {
```suggestion
    private static void validate(final String name) {
```
요건 어떤가요? 만약 초기화 파라미터로 name말고 다른 문자열이 들어왔다고 해보면, 
동일한 일을 하는 함수를 더 만들게 되는데 🤔 

이름을 검증한다. 라는의미는 아래와 같이 해도 충분히 전달 될거 같아요. 어떤가요?
```
validate(name);
```

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/domain/Round.java
> +    private static final int DO_NEXT_ROUND = 1;
변수명이 잘 안맞는거 같아요
ROUND_STEP 이라던지, 간격? 이라는 느낌을 표현해주는 변수명이 좋을거 같은데 어떤가요

2020-05-16 04:04 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +        MovingStrategy movingStrategy = new RandomMovingStrategy();
> 원래의 스트래티지 패턴에 따르면 Racing 에 전략을 두는 것이 맞는지

음... Racing에 인터페이스를 두는게 스트래티지 패턴에 문제 될 만한게 있나요 🤔🤔🤔🤔
스트래티지 패턴은 단순히 전략은 교체하기 쉽게 하기 위한 패턴으로 알고있는데 ❓

2020-05-16 04:25 UTC, gmlwjd9405 commented on src/main/java/racingcar/moving/RandomMovingStrategy.java
> +    public static final int BASE_LINE_NUM = 4;
그러네요... 피드백 주셨는데 적용을 못했네요...ㅎㅎ 
이런 경우에 디폴트로 지정하는걸 확실히 알게 됐어요.
감사합니다! 😁

2020-05-16 04:27 UTC, gmlwjd9405 commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
다른 더 좋은 방법을 찾아봐야 될 거 같아요..! 🤔

2020-05-16 04:39 UTC, gmlwjd9405 commented on src/main/java/racingcar/RacingGame.java
> +        MovingStrategy movingStrategy = new RandomMovingStrategy();
그렇다면 Racing 에서 MovingStrategy 를 가지고 있을 때, 즉 생성과 동시에 전략이 설정이 됐을 때의 이점을 생각을 해봐야 될 거 같아요! 

전략을 쉽게 교체하기 위해서라면 단순히 Racing 을 run 할 때 주입하는 것과 무슨 차이가 있는 걸까요? :astonished::astonished::astonished:

Racing 가 MovingStrategy 를 변수로 가지고 있는 경우
- (+) 이동 전략이 경주와 관련이 있음을 명시적으로 나타냄
- (-) 생성과 동시에 전략이 설정되면, 전략을 변경할 때마다 `updateMovingStrategy()` 호출 후 `racing.run()` 수행

등 (추가 예정)

2020-05-16 04:42 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
아녘ㅋㅋㅋㅋ 그냥 넘어가도 돼요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2020-05-16 04:43 UTC, nokchax commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
다만 그냥
```
private static final String FOUR_VALUES = "name1,name2,name3,name4";
```
이런 방식이 간편할거 같아서ㅎ..

2020-05-16 04:46 UTC, gmlwjd9405 commented on src/main/java/racingcar/RacingGame.java
> +        Racing racing = Racing.of(Cars.of(carNames), Round.of(round));
당장 생각나는 예는 
Racing 이 아닌, CarExhibition(자동차 전시) 와 같은 내용으로 구현을 해야할 때 Racing 에서 carNames 를 받아 Cars 로 변환하는 로직이 중복으로 발생할 거 같은 느낌이 드네요.

Cars 라는 domain 을 그대로 이용하기에는 Cars 에서 carNames 를 받아 Car를 생성하는 것이 더 나을 것 같다는 생각인데, 어떠신가요? ㅎㅎ

2020-05-16 07:08 UTC, nokchax commented on src/main/java/racingcar/RacingGame.java
> +        Racing racing = Racing.of(Cars.of(carNames), Round.of(round));
전달이 잘못됐다 ㅎㅎ 아녀 제가 말씀드린 방식은 아래 코드처럼
그냥 정적 팩토리 메소드나, 생성자 내부에서 바이패스 시켜주는 방식을 말한거예요
```
public static Racing of(final String carNames, final int round) {
    return new Racing(Cars.of(carNames), Round.of(round));
}
```
or
```
private Racing(final String carNames, final int round) {
    this.cars = Cars.of(carNames);
    this.round = Round.of(round);
}
public static Racing of(final String carNames, final int round) {
    return new Racint(carNames, round);
}
```
그냥 넘겨주면 로직 중복이랄건 없을거 같아서.. 
선호도의 차이니까 두 방식 모두 문제될건 없을거 같아요ㅎㅎ

2020-05-16 07:10 UTC, merged